Repository eelston/326Group11, pull requests merged in 2025-04, with the labels that each got.

#40 Add frontend subfolders and init package.json
  .gitignore
  frontend/.DS_Store
  frontend/init.md
  frontend/settings-screen-page/.DS_Store
  frontend/src/components/BaseComponent/BaseComponent.js
  frontend/src/eventhub/EventHub.js
  frontend/src/eventhub/Events.js
  frontend/src/main.css
  frontend/src/pages/LocationBrowsing/index.html
  frontend/src/pages/LocationBrowsing/style.css
  frontend/src/pages/LogInSignUp/log-in.html
  frontend/src/pages/LogInSignUp/sign-up.html
  frontend/src/pages/LogInSignUp/style.css
  frontend/src/pages/PostBrowsing/index.html
  frontend/src/pages/PostBrowsing/style.css
  frontend/src/pages/PostCreation/index.html
  frontend/src/pages/PostCreation/style.css
  frontend/src/pages/PostViewing/index.html
  frontend/src/pages/PostViewing/style.css
  frontend/src/pages/Settings/settings-screen.css
  frontend/src/pages/Settings/settings-screen.html
  frontend/src/pages/UserProfile/index.html
  frontend/src/pages/UserProfile/style.css
  package.json
Labels: organization

#46 Important edit to BaseComponent.js loadCSS()
  frontend/src/components/BaseComponent/BaseComponent.js
Labels: bug, data

#52 main.css Prelim update
  frontend/src/main.css
Labels: UI

#54 Add fake fetch() function from lecture
  frontend/src/services/Service.js
  frontend/src/utility/fetch.js
Labels: data

#60 Login and Signup: Improved Front-End Implementation with added JavaScript Functionality
  frontend/src/eventhub/LoginEvents.js
  frontend/src/lib/jsonServers/fakeUsers.json
  frontend/src/main.css
  frontend/src/pages/LogInSignUp/index.html
  frontend/src/pages/LogInSignUp/log-in.html
  frontend/src/pages/LogInSignUp/main.js
  frontend/src/pages/LogInSignUp/sign-up.html
  frontend/src/pages/LogInSignUp/style.css
  frontend/src/pages/LogInSignUp/styles.css
  frontend/src/services/UserAuthenticationService.js
  frontend/src/services/UserRepository.js
  frontend/src/utility/fetchUsers.js
Labels: enhancement, UI

#63 Location Browsing Screen Frontend Implementation
  frontend/src/components/BaseComponent/BaseComponent.js
  frontend/src/components/LocationBrowsingComponent/LocationBrowsingComponent.css
  frontend/src/components/LocationBrowsingComponent/LocationBrowsingComponent.js
  frontend/src/components/LocationCardComponent/CrowdingHints.js
  frontend/src/components/LocationCardComponent/LocationCardComponent.css
  frontend/src/components/LocationCardComponent/LocationCardComponent.js
  frontend/src/lib/data/MockLocations.js
  frontend/src/pages/LocationBrowsing/index.html
  frontend/src/pages/LocationBrowsing/script.js
  frontend/src/pages/LocationBrowsing/style.css
  frontend/src/services/LocationRepositoryRemoteFakeService.js
  frontend/src/utility/fetchLocations.js
  package-lock.json
  package.json
Labels: UI

#65 Upload Milestone 5 Summary PDF
  team/m5/CS 326 Milestone 5 Summary.pdf
Labels: documentation, team

#68 Setup Express server dependencies & organized files for Milestone 6
  .gitignore
  backend/src/server.js
  frontend/src/components/PostBrowsingComponent/PostBrowsingComponent.css
  frontend/src/components/PostBrowsingComponent/PostBrowsingComponent.js
  frontend/src/components/PostViewingComponent/PostViewingComponent.css
  frontend/src/components/PostViewingComponent/PostViewingComponent.js
  frontend/src/eventhub/LoginEvents.js
  frontend/src/lib/data/MockCourses.js
  frontend/src/lib/data/MockFeed.js
  frontend/src/lib/data/MockUser.js
  frontend/src/pages/LocationBrowsing/index.html
  frontend/src/pages/LocationBrowsing/script.js
  frontend/src/pages/LogInSignUp/index.html
  frontend/src/pages/LogInSignUp/style.css
  frontend/src/pages/PostBrowsing/index.html
  frontend/src/pages/PostBrowsing/script.js
  frontend/src/pages/PostCreation/index.html
  frontend/src/pages/PostCreation/style.css
  frontend/src/pages/PostViewing/index.html
  frontend/src/pages/PostViewing/script.js
  frontend/src/pages/Settings/script.js
  frontend/src/pages/UserProfile/index.html
  frontend/src/pages/UserProfile/script.js
  frontend/src/services/Service.js
  package-lock.json
  package.json
Labels: dependencies

#70 Clean up Location Browsing Page events
  .gitignore
  frontend/src/components/LocationBrowsingComponent/LocationBrowsingComponent.js
  frontend/src/components/LocationCardComponent/LocationCardComponent.js
  frontend/src/eventhub/Events.js
Labels: UI

#74 Crowding report modal
  frontend/src/components/LocationBrowsingComponent/LocationBrowsingComponent.css
  frontend/src/components/LocationBrowsingComponent/LocationBrowsingComponent.js
  frontend/src/components/LocationCardComponent/LocationCardComponent.js
  frontend/src/eventhub/Events.js
Labels: UI

#72 Updates to main.css color variables; navbar component & basic navigation dropdown implementation
  frontend/src/components/LocationBrowsingComponent/LocationBrowsingComponent.css
  frontend/src/components/LocationBrowsingComponent/LocationBrowsingComponent.js
  frontend/src/components/LocationCardComponent/LocationCardComponent.css
  frontend/src/components/NavbarComponent/NavbarComponent.css
  frontend/src/components/NavbarComponent/NavbarComponent.js
  frontend/src/components/PostBrowsingComponent/PostBrowsingComponent.css
  frontend/src/components/PostViewingComponent/PostViewingComponent.css
  frontend/src/main.css
  frontend/src/pages/LocationBrowsing/index.html
  frontend/src/pages/LocationBrowsing/script.js
  frontend/src/pages/LocationBrowsing/style.css
  frontend/src/pages/LogInSignUp/index.html
  frontend/src/pages/PostBrowsing/index.html
  frontend/src/pages/PostBrowsing/script.js
  frontend/src/pages/PostViewing/index.html
  frontend/src/pages/PostViewing/script.js
  frontend/src/pages/Settings/index.html
  frontend/src/pages/Settings/script.js
  frontend/src/pages/UserProfile/index.html
  frontend/src/pages/UserProfile/script.js
Labels: UI

#81 Backend Implementation for Settings Screen
  backend/src/controllers/settings.js
  backend/src/models/settings.js
  backend/src/routes/settings.js
  backend/src/server.js
  frontend/src/eventhub/SettingsEvents.js
  frontend/src/pages/Settings/index.html
  frontend/src/pages/Settings/script.js
  frontend/src/pages/Settings/style.css
  frontend/src/services/SettingsRepositoryService.js
Labels: UI, server

#85 Crowding Score Report Integration
  backend/locations/controller.js
  backend/locations/routes.js
  backend/reports/controller.js
  backend/reports/report.js
  backend/reports/routes.js
  backend/src/data/locations.json
  backend/src/server.js
  frontend/src/components/LocationBrowsingComponent/LocationBrowsingComponent.js
  frontend/src/components/LocationCardComponent/LocationCardComponent.css
  frontend/src/components/LocationCardComponent/LocationCardComponent.js
  frontend/src/eventhub/Events.js
  frontend/src/lib/data/MockLocations.js
  frontend/src/pages/LocationBrowsing/index.html
  frontend/src/pages/LocationBrowsing/script.js
  frontend/src/services/ReportRepositoryRemoteService.js
  frontend/src/services/Service.js
Labels: UI, data, server

#87 Upload Milestone 6 Summary PDF
  team/m6/CS 326 Milestone 6 Summary.pdf
Labels: documentation, team

#88 Add SQLite and Sequelize packages
  frontend/src/components/LocationBrowsingComponent/LocationBrowsingComponent.js
  package-lock.json
  package.json
Labels: dependencies
